//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SMPEntities : DbContext
    {
        public DB_SMPEntities()
            : base("name=DB_SMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CAT> TB_CAT { get; set; }
        public virtual DbSet<TB_SUPP> TB_SUPP { get; set; }
        public virtual DbSet<TB_PUR> TB_PUR { get; set; }
        public virtual DbSet<TB_CUS> TB_CUS { get; set; }
        public virtual DbSet<TB_SELL> TB_SELL { get; set; }
        public virtual DbSet<TB_USERS> TB_USERS { get; set; }
    }
}
