//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        public int ID { get; set; }
        public string Users_Name { get; set; }
        public string Users_Pass { get; set; }
        public string Users_Roll { get; set; }
        public string User_State { get; set; }
        public byte[] User_Image { get; set; }
    }
}
